package main

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"text/template"
)

type ruleTemplateData struct {
	RuleName string
	TypeName string
	RuleID   string
}

type ciTemplateDefinition struct {
	relativePath string
	content      string
}

type docsTemplateDefinition struct {
	format       string
	relativePath string
	content      string
}

// RuleTemplateGenerator generates rule templates
type RuleTemplateGenerator struct {
	rulesDir string
}

// CITemplateGenerator generates CI pipeline templates.
type CITemplateGenerator struct {
	baseDir string
}

// DocsGenerator generates architecture documentation outputs.
type DocsGenerator struct {
	baseDir string
}

// NewRuleTemplateGenerator creates a new generator
func NewRuleTemplateGenerator(rulesDir string) *RuleTemplateGenerator {
	return &RuleTemplateGenerator{
		rulesDir: rulesDir,
	}
}

// NewCITemplateGenerator creates a new CI template generator.
func NewCITemplateGenerator(baseDir string) *CITemplateGenerator {
	return &CITemplateGenerator{baseDir: baseDir}
}

// NewDocsGenerator creates a new documentation generator.
func NewDocsGenerator(baseDir string) *DocsGenerator {
	return &DocsGenerator{baseDir: baseDir}
}

// Generate creates documentation in selected format.
// Existing files are never overwritten directly; changed content is written to *.new.
func (g *DocsGenerator) Generate(format string) error {
	definition, err := resolveDocsTemplateDefinition(format)
	if err != nil {
		return err
	}

	targetPath := filepath.Join(g.baseDir, definition.relativePath)
	if err := os.MkdirAll(filepath.Dir(targetPath), 0755); err != nil {
		return fmt.Errorf("failed to create docs directory: %w", err)
	}

	existing, readErr := os.ReadFile(targetPath)
	if readErr != nil && !os.IsNotExist(readErr) {
		return fmt.Errorf("failed reading docs target: %w", readErr)
	}

	if os.IsNotExist(readErr) {
		if err := os.WriteFile(targetPath, []byte(definition.content), 0644); err != nil {
			return fmt.Errorf("failed writing docs file: %w", err)
		}
		fmt.Printf("✅ Documentation created: %s\n", targetPath)
		return nil
	}

	if string(existing) == definition.content {
		fmt.Printf("ℹ Documentation is up to date: %s\n", targetPath)
		return nil
	}

	previewPath := targetPath + ".new"
	if err := os.WriteFile(previewPath, []byte(definition.content), 0644); err != nil {
		return fmt.Errorf("failed writing docs preview file: %w", err)
	}

	fmt.Printf("⚠ Existing file not overwritten: %s\n", targetPath)
	fmt.Printf("📝 Generated preview: %s\n", previewPath)
	diff := buildLineDiff(existing, []byte(definition.content), 8)
	if len(diff) > 0 {
		fmt.Println("Diff preview:")
		for _, line := range diff {
			fmt.Println(line)
		}
	}

	return nil
}

func resolveDocsTemplateDefinition(format string) (docsTemplateDefinition, error) {
	switch strings.ToLower(strings.TrimSpace(format)) {
	case "markdown", "md":
		return docsTemplateDefinition{
			format:       "markdown",
			relativePath: filepath.Join("docs", "architecture.generated.md"),
			content:      markdownDocsTemplate,
		}, nil
	case "mermaid", "mmd":
		return docsTemplateDefinition{
			format:       "mermaid",
			relativePath: filepath.Join("docs", "architecture.generated.mmd"),
			content:      mermaidDocsTemplate,
		}, nil
	default:
		return docsTemplateDefinition{}, fmt.Errorf("unsupported docs format %q (supported: markdown, mermaid)", format)
	}
}

func buildLineDiff(before, after []byte, maxLines int) []string {
	beforeLines := strings.Split(strings.ReplaceAll(string(before), "\r\n", "\n"), "\n")
	afterLines := strings.Split(strings.ReplaceAll(string(after), "\r\n", "\n"), "\n")

	if maxLines <= 0 {
		maxLines = 8
	}

	limit := len(beforeLines)
	if len(afterLines) > limit {
		limit = len(afterLines)
	}

	result := make([]string, 0, maxLines)
	for i := 0; i < limit && len(result) < maxLines; i++ {
		var left, right string
		if i < len(beforeLines) {
			left = beforeLines[i]
		}
		if i < len(afterLines) {
			right = afterLines[i]
		}
		if left == right {
			continue
		}
		if left != "" {
			result = append(result, fmt.Sprintf("- %d:%s", i+1, left))
		}
		if right != "" {
			result = append(result, fmt.Sprintf("+ %d:%s", i+1, right))
		}
	}

	return result
}

const markdownDocsTemplate = `# RepoDoctor Architecture (Generated)

This file is generated by:

` + "```" + `bash
repodoctor generate docs --format markdown
` + "```" + `

## Layering

- CLI/root package orchestrates command execution
- ` + "`internal/analysis`" + ` handles analysis orchestration
- ` + "`internal/languages`" + ` contains language adapters
- ` + "`internal/rules`" + ` contains rule implementations
- ` + "`internal/model`" + ` and ` + "`internal/domain`" + ` remain pure core data/contracts

## Notes

- Output is deterministic.
- Existing docs are never overwritten directly; changed generations create .new preview files.
`

const mermaidDocsTemplate = `%% RepoDoctor Architecture (Generated)
graph TD
    CLI[main / CLI] --> ANALYSIS[internal/analysis]
    ANALYSIS --> LANG[internal/languages]
    ANALYSIS --> MODEL[internal/model]
    ANALYSIS --> DOMAIN[internal/domain]
    CLI --> RULES[internal/rules]
    RULES --> MODEL
    RULES --> DOMAIN
`

// Generate creates the CI template for the selected provider.
func (g *CITemplateGenerator) Generate(provider string, force bool) error {
	definition, err := resolveCITemplateDefinition(provider)
	if err != nil {
		return err
	}

	targetPath := filepath.Join(g.baseDir, definition.relativePath)
	if err := os.MkdirAll(filepath.Dir(targetPath), 0755); err != nil {
		return fmt.Errorf("failed to create CI template directory: %w", err)
	}

	if _, err := os.Stat(targetPath); err == nil && !force {
		return fmt.Errorf("CI template already exists: %s (use --force to overwrite)", targetPath)
	}

	if err := os.WriteFile(targetPath, []byte(definition.content), 0644); err != nil {
		return fmt.Errorf("failed to write CI template: %w", err)
	}

	fmt.Printf("✅ CI template created: %s\n", targetPath)
	return nil
}

func resolveCITemplateDefinition(provider string) (ciTemplateDefinition, error) {
	switch strings.ToLower(strings.TrimSpace(provider)) {
	case "github":
		return ciTemplateDefinition{relativePath: filepath.Join(".github", "workflows", "repodoctor.yml"), content: githubActionsTemplate}, nil
	case "gitlab":
		return ciTemplateDefinition{relativePath: ".gitlab-ci.yml", content: gitlabCITemplate}, nil
	case "azure":
		return ciTemplateDefinition{relativePath: "azure-pipelines.yml", content: azurePipelinesTemplate}, nil
	default:
		return ciTemplateDefinition{}, fmt.Errorf("unsupported CI provider %q (supported: github, gitlab, azure)", provider)
	}
}

const githubActionsTemplate = `name: repodoctor

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]

jobs:
  repodoctor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Test
        run: go test ./...

      - name: Vet
        run: go vet ./...

      - name: Structural Analysis
        run: go run . analyze -path .
`

const gitlabCITemplate = `stages:
  - test

repodoctor:
  stage: test
  image: golang:1.24
  script:
    - go test ./...
    - go vet ./...
    - go run . analyze -path .
`

const azurePipelinesTemplate = `trigger:
  branches:
    include:
      - main
      - dev

pool:
  vmImage: ubuntu-latest

steps:
  - task: GoTool@0
    inputs:
      version: "1.24"

  - script: go test ./...
    displayName: Test

  - script: go vet ./...
    displayName: Vet

  - script: go run . analyze -path .
    displayName: Structural Analysis
`

// Generate creates a new rule template file
func (g *RuleTemplateGenerator) Generate(ruleName string) error {
	sanitized, err := sanitizeRuleName(ruleName)
	if err != nil {
		return err
	}

	return g.generateTemplateFiles(sanitized)
}

func (g *RuleTemplateGenerator) generateTemplateFiles(sanitized string) error {

	// Create rules directory if it doesn't exist
	if err := os.MkdirAll(g.rulesDir, 0755); err != nil {
		return fmt.Errorf("failed to create rules directory: %w", err)
	}

	// Generate file name
	fileName := strings.ReplaceAll(sanitized, "-", "_") + "_rule.go"
	filePath := filepath.Join(g.rulesDir, fileName)

	// Check if file already exists
	if _, err := os.Stat(filePath); err == nil {
		return fmt.Errorf("rule file already exists: %s", filePath)
	}

	// Generate template content
	content := g.generateTemplate(sanitized)

	// Write file
	if err := os.WriteFile(filePath, []byte(content), 0644); err != nil {
		return fmt.Errorf("failed to write rule file: %w", err)
	}

	fmt.Printf("✅ Rule template created: %s\n", filePath)
	fmt.Printf("\nNext steps:\n")
	fmt.Printf("1. Implement the Evaluate method\n")
	fmt.Printf("2. Add the rule to the rule registry\n")
	fmt.Printf("3. Write tests for the new rule\n\n")

	return nil
}

// generateTemplate creates the rule template content
func (g *RuleTemplateGenerator) generateTemplate(ruleName string) string {
	typeName := ruleTypeName(ruleName)
	data := g.buildRuleTemplateData(ruleName, typeName)

	content, err := g.renderRuleTemplate(data)
	if err != nil {
		return g.generateSimpleTemplate(ruleName, typeName)
	}

	return content
}

func (g *RuleTemplateGenerator) buildRuleTemplateData(ruleName, typeName string) ruleTemplateData {
	return ruleTemplateData{
		RuleName: ruleName,
		TypeName: typeName,
		RuleID:   strings.ReplaceAll(ruleName, "-", "_"),
	}
}

func (g *RuleTemplateGenerator) renderRuleTemplate(data ruleTemplateData) (string, error) {
	t, err := template.New("rule").Parse(g.ruleTemplateText())
	if err != nil {
		return "", err
	}

	var builder strings.Builder
	if err := t.Execute(&builder, data); err != nil {
		return "", err
	}

	return builder.String(), nil
}

func (g *RuleTemplateGenerator) ruleTemplateText() string {
	return `package rules

import (
	"RepoDoctor/internal/model"
)

// {{.TypeName}}Rule detects {{.RuleName}} violations.
type {{.TypeName}}Rule struct{}

// New{{.TypeName}}Rule creates a new {{.TypeName}}Rule instance.
func New{{.TypeName}}Rule() *{{.TypeName}}Rule {
	return &{{.TypeName}}Rule{}
}

// ID returns the unique identifier for this rule.
func (r *{{.TypeName}}Rule) ID() string {
	return "rule.{{.RuleID}}"
}

// Category returns the rule category.
func (r *{{.TypeName}}Rule) Category() string {
	return "maintainability"
}

// Severity returns the default severity.
func (r *{{.TypeName}}Rule) Severity() string {
	return "warning"
}

// Evaluate checks for {{.RuleName}} violations in the analysis context.
// This signature matches internal/rules.Rule interface.
func (r *{{.TypeName}}Rule) Evaluate(context AnalysisContext) []model.Violation {
	var violations []model.Violation
	// TODO: Implement rule evaluation logic
	return violations
}

// AnalysisContext mirrors internal/rules.AnalysisContext.
// NOTE: When moving this rule into internal/rules/, remove this type
// and use the AnalysisContext defined in that package instead.
type AnalysisContext struct {
	RepositoryFiles []RepositoryFile
}

// RepositoryFile represents a source file for analysis.
type RepositoryFile struct {
	Path    string
	Content string
	Imports []string
}
`
}

const simpleRuleTemplate = `package rules

import (
	"RepoDoctor/internal/model"
)

// %sRule detects %s violations.
type %sRule struct{}

// New%sRule creates a new %sRule instance.
func New%sRule() *%sRule {
	return &%sRule{}
}

// ID returns the unique identifier for this rule.
func (r *%sRule) ID() string {
	return "rule.%s"
}

// Category returns the rule category.
func (r *%sRule) Category() string {
	return "maintainability"
}

// Severity returns the default severity.
func (r *%sRule) Severity() string {
	return "warning"
}

// Evaluate checks for %s violations in the analysis context.
func (r *%sRule) Evaluate(context AnalysisContext) []model.Violation {
	var violations []model.Violation
	// TODO: Implement rule evaluation logic
	return violations
}

// AnalysisContext mirrors internal/rules.AnalysisContext.
type AnalysisContext struct {
	RepositoryFiles []RepositoryFile
}

// RepositoryFile represents a source file for analysis.
type RepositoryFile struct {
	Path    string
	Content string
	Imports []string
}
`

// generateSimpleTemplate creates a simpler template if template rendering fails
func (g *RuleTemplateGenerator) generateSimpleTemplate(ruleName, typeName string) string {
	ruleID := strings.ReplaceAll(ruleName, "-", "_")

	return fmt.Sprintf(
		simpleRuleTemplate,
		typeName, ruleName, typeName,
		typeName, typeName, typeName, typeName, typeName,
		typeName, ruleID,
		typeName,
		typeName,
		ruleName,
		typeName,
	)
}

// GenerateWithTest generates both rule template and test file
func (g *RuleTemplateGenerator) GenerateWithTest(ruleName string) error {
	sanitized, err := sanitizeRuleName(ruleName)
	if err != nil {
		return err
	}

	if err := g.generateTemplateFiles(sanitized); err != nil {
		return err
	}

	// Generate test file
	testFileName := strings.ReplaceAll(sanitized, "-", "_") + "_rule_test.go"
	testFilePath := filepath.Join(g.rulesDir, testFileName)

	testContent := g.generateTestTemplate(sanitized)

	if err := os.WriteFile(testFilePath, []byte(testContent), 0644); err != nil {
		return fmt.Errorf("failed to write test file: %w", err)
	}

	fmt.Printf("✅ Test template created: %s\n", testFilePath)

	return nil
}

// generateTestTemplate creates a test template
func (g *RuleTemplateGenerator) generateTestTemplate(ruleName string) string {
	typeName := ruleTypeName(ruleName)

	return fmt.Sprintf(`package rules

import (
	"testing"
)

func Test%sRule_ID(t *testing.T) {
	rule := New%sRule()
	
	expected := "rule.%s"
	if rule.ID() != expected {
		t.Errorf("Expected ID %%s, got %%s", expected, rule.ID())
	}
}

func Test%sRule_Category(t *testing.T) {
	rule := New%sRule()
	
	if rule.Category() == "" {
		t.Error("Expected non-empty category")
	}
}

func Test%sRule_Severity(t *testing.T) {
	rule := New%sRule()
	
	if rule.Severity() == "" {
		t.Error("Expected non-empty severity")
	}
}

func Test%sRule_Evaluate(t *testing.T) {
	rule := New%sRule()
	
	violations := rule.Evaluate(AnalysisContext{})
	if violations == nil {
		t.Fatal("expected non-nil violations slice")
	}
}
`, typeName, typeName, strings.ReplaceAll(ruleName, "-", "_"),
		typeName, typeName,
		typeName, typeName,
		typeName, typeName)
}

func sanitizeRuleName(ruleName string) (string, error) {
	trimmed := strings.TrimSpace(strings.ToLower(ruleName))
	if trimmed == "" {
		return "", fmt.Errorf("rule name cannot be empty")
	}

	normalized := strings.ReplaceAll(trimmed, " ", "-")
	normalized = strings.ReplaceAll(normalized, "_", "-")
	normalized = strings.Trim(normalized, "-")

	validName := regexp.MustCompile(`^[a-z0-9-]+$`)
	if !validName.MatchString(normalized) {
		return "", fmt.Errorf("invalid rule name %q: use only letters, numbers, spaces, underscore or hyphen", ruleName)
	}

	return normalized, nil
}

func ruleTypeName(ruleName string) string {
	parts := strings.FieldsFunc(ruleName, func(r rune) bool {
		return r == '-' || r == '_'
	})

	var builder strings.Builder
	for _, part := range parts {
		if part == "" {
			continue
		}
		builder.WriteString(strings.ToUpper(part[:1]))
		if len(part) > 1 {
			builder.WriteString(part[1:])
		}
	}

	if builder.Len() == 0 {
		return "Custom"
	}

	return builder.String()
}
